apiVersion: v1               #versión de la api de kubernetes
kind: Pod
metadata:                    #etiquetas o nombres
  name: nginxpod             #set pod name nginxpod
spec:                        #declarar los contenedores (todos tendrán la misma ip)
  containers:                #un solo contenedor con una imagen nginx:alpine y de nombre nginxcontainer
    - name: nginxcontainer
      image: nginx:alpine