version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: movies-mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moviesdb
      MYSQL_USER: movieuser
      MYSQL_PASSWORD: moviepass
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
